import { Question } from './types';

/**
 * Kamen Rider Song Database (30 Iconic Themes from mp4/song)
 * Features themes across Reiwa, Heisei Phase 1 & 2.
 * Includes local audio MP3 files, album metadata, theme colors, and era classifications.
 */
export const QUESTIONS: Question[] = [
  {
    id: 1,
    songTitle: 'EXCITE',
    series: 'Kamen Rider Ex-Aid',
    artist: 'Daichi Miura (三浦大知)',
    albumTitle: 'EXCITE [Single]',
    era: 'Heisei',
    themeColor: '#fa0079',
    audioUrl: '/songs/ex-aid.mp3',
    youtubeId: 'E13jVMczRJg',
    options: ['Kamen Rider Ex-Aid', 'Kamen Rider Build', 'Kamen Rider Ghost', 'Kamen Rider Drive'],
    correctIndex: 0,
  },
  {
    id: 2,
    songTitle: 'Be The One',
    series: 'Kamen Rider Build',
    artist: 'PANDORA feat. Beverly',
    albumTitle: 'Be The One [Single]',
    era: 'Heisei',
    themeColor: '#2563eb',
    audioUrl: '/songs/build.mp3',
    youtubeId: 'fRSaJp362bM',
    options: ['Kamen Rider Zi-O', 'Kamen Rider Build', 'Kamen Rider Gaim', 'Kamen Rider Wizard'],
    correctIndex: 1,
  },
  {
    id: 3,
    songTitle: 'REAL×EYEZ',
    series: 'Kamen Rider Zero-One',
    artist: 'J×Takanori Nishikawa',
    albumTitle: 'REAL×EYEZ [Single]',
    era: 'Reiwa',
    themeColor: '#a3e635',
    audioUrl: '/songs/zero-one.mp3',
    youtubeId: '1BG0k2FkDME',
    options: ['Kamen Rider Saber', 'Kamen Rider Geats', 'Kamen Rider Zero-One', 'Kamen Rider Revice'],
    correctIndex: 2,
  },
  {
    id: 4,
    songTitle: 'Anything Goes!',
    series: 'Kamen Rider OOO',
    artist: 'Maki Ohguro (大黒摩季)',
    albumTitle: 'Anything Goes! [Single]',
    era: 'Heisei',
    themeColor: '#f59e0b',
    audioUrl: '/songs/ooo.mp3',
    youtubeId: 'qlmonFKz9YY',
    options: ['Kamen Rider Fourze', 'Kamen Rider W', 'Kamen Rider Decade', 'Kamen Rider OOO'],
    correctIndex: 3,
  },
  {
    id: 5,
    songTitle: 'Switch On!',
    series: 'Kamen Rider Fourze',
    artist: 'Anna Tsuchiya (土屋アンナ)',
    albumTitle: 'Switch On! [Single]',
    era: 'Heisei',
    themeColor: '#38bdf8',
    audioUrl: '/songs/fourze.mp3',
    youtubeId: 'h0jgHKWQmIY',
    options: ['Kamen Rider Fourze', 'Kamen Rider OOO', 'Kamen Rider Wizard', 'Kamen Rider Gaim'],
    correctIndex: 0,
  },
  {
    id: 6,
    songTitle: 'JUST LIVE MORE',
    series: 'Kamen Rider Gaim',
    artist: 'Gaim no Kaze (鎧武乃風)',
    albumTitle: 'JUST LIVE MORE [Single]',
    era: 'Heisei',
    themeColor: '#ea580c',
    audioUrl: '/songs/gaim.mp3',
    youtubeId: '3kbTAx4RQWM',
    options: ['Kamen Rider Drive', 'Kamen Rider Gaim', 'Kamen Rider Ghost', 'Kamen Rider Ex-Aid'],
    correctIndex: 1,
  },
  {
    id: 7,
    songTitle: 'SURPRISE-DRIVE',
    series: 'Kamen Rider Drive',
    artist: 'Mitsuru Matsuoka EARNEST DRIVE',
    albumTitle: 'SURPRISE-DRIVE [Single]',
    era: 'Heisei',
    themeColor: '#dc2626',
    audioUrl: '/songs/drive.mp3',
    youtubeId: 'k3p-R4vRvdQ',
    options: ['Kamen Rider Gaim', 'Kamen Rider Ghost', 'Kamen Rider Drive', 'Kamen Rider Ex-Aid'],
    correctIndex: 2,
  },
  {
    id: 8,
    songTitle: 'Warera Omou, Yue Ni Warera Ari (我思う、故に我あり)',
    series: 'Kamen Rider Ghost',
    artist: 'Kishidan (氣志團)',
    albumTitle: '我思う、故に我あり [Single]',
    era: 'Heisei',
    themeColor: '#fb923c',
    audioUrl: '/songs/ghost.mp3',
    youtubeId: 'SB9GCaHtYcg',
    options: ['Kamen Rider Wizard', 'Kamen Rider Fourze', 'Kamen Rider OOO', 'Kamen Rider Ghost'],
    correctIndex: 3,
  },
  {
    id: 9,
    songTitle: 'Life is SHOW TIME',
    series: 'Kamen Rider Wizard',
    artist: 'Shō Kiryūin (Golden Bomber)',
    albumTitle: 'Life is SHOW TIME [Single]',
    era: 'Heisei',
    themeColor: '#e11d48',
    audioUrl: '/songs/wizard.mp3',
    youtubeId: 'mI_OgdNmrmI',
    options: ['Kamen Rider Wizard', 'Kamen Rider Decade', 'Kamen Rider W', 'Kamen Rider Kabuto'],
    correctIndex: 0,
  },
  {
    id: 10,
    songTitle: 'ALMIGHTY～仮面の約束',
    series: 'Kamen Rider Saber',
    artist: 'Tokyo Ska Paradise Orchestra feat. Yoohei Kawakami',
    albumTitle: 'ALMIGHTY～仮面の約束 [Single]',
    era: 'Reiwa',
    themeColor: '#b91c1c',
    audioUrl: '/songs/saber.mp3',
    youtubeId: 'Zj4-3UELQeQ',
    options: ['Kamen Rider Revice', 'Kamen Rider Saber', 'Kamen Rider Zero-One', 'Kamen Rider Zi-O'],
    correctIndex: 1,
  },
  {
    id: 11,
    songTitle: 'Over "Quartzer"',
    series: 'Kamen Rider Zi-O',
    artist: 'Shuta Sueyoshi feat. ISSA',
    albumTitle: 'Over "Quartzer" [Single]',
    era: 'Heisei',
    themeColor: '#c084fc',
    audioUrl: '/songs/zi-o.mp3',
    youtubeId: 'QLEfM8YZEGI',
    options: ['Kamen Rider Build', 'Kamen Rider Zero-One', 'Kamen Rider Zi-O', 'Kamen Rider Geats'],
    correctIndex: 2,
  },
  {
    id: 12,
    songTitle: 'W-B-X ～W-Boiled Extreme～',
    series: 'Kamen Rider W',
    artist: 'Aya Kamiki with TAKUYA',
    albumTitle: 'W-B-X ~W-Boiled Extreme~ [Single]',
    era: 'Heisei',
    themeColor: '#10b981',
    audioUrl: '/songs/w.mp3',
    youtubeId: 'NeWMadV5B-4',
    options: ['Kamen Rider Decade', 'Kamen Rider OOO', 'Kamen Rider Fourze', 'Kamen Rider W'],
    correctIndex: 3,
  },
  {
    id: 13,
    songTitle: 'Journey through the Decade',
    series: 'Kamen Rider Decade',
    artist: 'Gackt',
    albumTitle: 'Journey through the Decade [Single]',
    era: 'Heisei',
    themeColor: '#ec4899',
    audioUrl: '/songs/decade.mp3',
    youtubeId: 'KvzPCITqe2s',
    options: ['Kamen Rider Decade', 'Kamen Rider Zi-O', 'Kamen Rider Den-O', 'Kamen Rider Kiva'],
    correctIndex: 0,
  },
  {
    id: 14,
    songTitle: 'PLAY BACK',
    series: 'Kamen Rider Zeztz',
    artist: 'Yuta',
    albumTitle: 'PLAY BACK [Single]',
    era: 'Reiwa',
    themeColor: '#06b6d4',
    audioUrl: '/songs/zeztz-playback.mp3',
    youtubeId: 'FZjvLGy9sIw',
    options: ['Kamen Rider Gotchard', 'Kamen Rider Zeztz', 'Kamen Rider Gavv', 'Kamen Rider Geats'],
    correctIndex: 1,
  },
  {
    id: 15,
    songTitle: 'Trust・Last',
    series: 'Kamen Rider Geats',
    artist: 'Koda Kumi × Shonan no Kaze',
    albumTitle: 'Trust・Last [Single]',
    era: 'Reiwa',
    themeColor: '#f43f5e',
    audioUrl: '/songs/geats.mp3',
    youtubeId: 'w1j6QvQ5y-c',
    options: ['Kamen Rider Revice', 'Kamen Rider Saber', 'Kamen Rider Geats', 'Kamen Rider Gotchard'],
    correctIndex: 2,
  },
  {
    id: 16,
    songTitle: 'CHEMY×STORY',
    series: 'Kamen Rider Gotchard',
    artist: 'BACK-ON × FLOW',
    albumTitle: 'CHEMY×STORY [Single]',
    era: 'Reiwa',
    themeColor: '#0ea5e9',
    audioUrl: '/songs/gotchard.mp3',
    youtubeId: 'M2uE_5p5n64',
    options: ['Kamen Rider Geats', 'Kamen Rider Gavv', 'Kamen Rider Saber', 'Kamen Rider Gotchard'],
    correctIndex: 3,
  },
  {
    id: 17,
    songTitle: 'Got Boost?',
    series: 'Kamen Rider Gavv',
    artist: 'FANTASTICS from EXILE TRIBE',
    albumTitle: 'Got Boost? [Single]',
    era: 'Reiwa',
    themeColor: '#8b5cf6',
    audioUrl: '/songs/gavv.mp3',
    youtubeId: 'E13jVMczRJg',
    options: ['Kamen Rider Gavv', 'Kamen Rider Gotchard', 'Kamen Rider Geats', 'Kamen Rider Revice'],
    correctIndex: 0,
  },
  {
    id: 18,
    songTitle: 'Climax Jump',
    series: 'Kamen Rider Den-O',
    artist: 'AAA DEN-O form',
    albumTitle: 'Climax Jump [Single]',
    era: 'Heisei',
    themeColor: '#f97316',
    audioUrl: '/songs/den-o.mp3',
    youtubeId: 'rF7pD4g4dGk',
    options: ['Kamen Rider Kiva', 'Kamen Rider Den-O', 'Kamen Rider Kabuto', 'Kamen Rider Blade'],
    correctIndex: 1,
  },
  {
    id: 19,
    songTitle: 'Break the Chain',
    series: 'Kamen Rider Kiva',
    artist: 'Tourbillon',
    albumTitle: 'Break the Chain [Single]',
    era: 'Heisei',
    themeColor: '#e11d48',
    audioUrl: '/songs/kiva.mp3',
    youtubeId: 'qE04K_nJq20',
    options: ['Kamen Rider Decade', 'Kamen Rider Den-O', 'Kamen Rider Kiva', 'Kamen Rider Kabuto'],
    correctIndex: 2,
  },
  {
    id: 20,
    songTitle: 'NEXT LEVEL',
    series: 'Kamen Rider Kabuto',
    artist: 'YU-KI (TRF)',
    albumTitle: 'NEXT LEVEL [Single]',
    era: 'Heisei',
    themeColor: '#b91c1c',
    audioUrl: '/songs/kabuto.mp3',
    youtubeId: 'zYj58w_oQ48',
    options: ['Kamen Rider 555', 'Kamen Rider Blade', 'Kamen Rider Hibiki', 'Kamen Rider Kabuto'],
    correctIndex: 3,
  },
  {
    id: 21,
    songTitle: 'Kagayaki / Shounen yo',
    series: 'Kamen Rider Hibiki',
    artist: 'Toshihiko Sahashi / Akira Fuse',
    albumTitle: 'Kamen Rider Hibiki OST',
    era: 'Heisei',
    themeColor: '#7c3aed',
    audioUrl: '/songs/hibiki.mp3',
    youtubeId: '3kbTAx4RQWM',
    options: ['Kamen Rider Hibiki', 'Kamen Rider Blade', 'Kamen Rider Ryuki', 'Kamen Rider Agito'],
    correctIndex: 0,
  },
  {
    id: 22,
    songTitle: 'Round ZERO ~ BLADE BRAVE',
    series: 'Kamen Rider Blade',
    artist: 'Nanase Aikawa (相川七瀬)',
    albumTitle: 'Round ZERO ~ BLADE BRAVE [Single]',
    era: 'Heisei',
    themeColor: '#3b82f6',
    audioUrl: '/songs/blade.mp3',
    youtubeId: 'qT7U7X3C8m4',
    options: ['Kamen Rider 555', 'Kamen Rider Blade', 'Kamen Rider Ryuki', 'Kamen Rider Kabuto'],
    correctIndex: 1,
  },
  {
    id: 23,
    songTitle: 'Justiφ\'s',
    series: 'Kamen Rider 555',
    artist: 'ISSA (DA PUMP)',
    albumTitle: 'Justiφ\'s [Single]',
    era: 'Heisei',
    themeColor: '#ef4444',
    audioUrl: '/songs/faiz.mp3',
    youtubeId: 'e2XJcZqGq2E',
    options: ['Kamen Rider Agito', 'Kamen Rider Ryuki', 'Kamen Rider 555', 'Kamen Rider Blade'],
    correctIndex: 2,
  },
  {
    id: 24,
    songTitle: 'Alive A life',
    series: 'Kamen Rider Ryuki',
    artist: 'Rica Matsumoto (松本梨香)',
    albumTitle: 'Alive A life [Single]',
    era: 'Heisei',
    themeColor: '#dc2626',
    audioUrl: '/songs/ryuki.mp3',
    youtubeId: '1tY_2o3yKbg',
    options: ['Kamen Rider Kuuga', 'Kamen Rider Agito', 'Kamen Rider 555', 'Kamen Rider Ryuki'],
    correctIndex: 3,
  },
  {
    id: 25,
    songTitle: '仮面ライダーAGITO',
    series: 'Kamen Rider Agito',
    artist: 'Shinichi Ishihara (石原慎一)',
    albumTitle: '仮面ライダーAGITO [Single]',
    era: 'Heisei',
    themeColor: '#eab308',
    audioUrl: '/songs/agito.mp3',
    youtubeId: 'hH-yGq8K6aU',
    options: ['Kamen Rider Agito', 'Kamen Rider Kuuga', 'Kamen Rider Ryuki', 'Kamen Rider 555'],
    correctIndex: 0,
  },
  {
    id: 26,
    songTitle: '仮面ライダークウガ!',
    series: 'Kamen Rider Kuuga',
    artist: 'Masato Tanaka (田中昌之)',
    albumTitle: '仮面ライダークウガ! [Single]',
    era: 'Heisei',
    themeColor: '#991b1b',
    audioUrl: '/songs/kuuga.mp3',
    youtubeId: 'b-NfL6199R0',
    options: ['Kamen Rider Agito', 'Kamen Rider Kuuga', 'Kamen Rider Ryuki', 'Kamen Rider 555'],
    correctIndex: 1,
  },
  {
    id: 27,
    songTitle: 'ELEMENTS',
    series: 'Kamen Rider Blade',
    artist: 'RIDER CHIPS Featuring Ricky',
    albumTitle: 'ELEMENTS [Single]',
    era: 'Heisei',
    themeColor: '#2563eb',
    audioUrl: '/songs/blade-elements.mp3',
    youtubeId: 'Yv9VvE63lH4',
    options: ['Kamen Rider 555', 'Kamen Rider Ryuki', 'Kamen Rider Blade', 'Kamen Rider Kabuto'],
    correctIndex: 2,
  },
  {
    id: 28,
    songTitle: 'VISIONS',
    series: 'Kamen Rider Zeztz',
    artist: 'NAQT VANE',
    albumTitle: 'VISIONS [Single]',
    era: 'Reiwa',
    themeColor: '#a855f7',
    audioUrl: '/songs/zeztz-visions.mp3',
    youtubeId: 'qlmonFKz9YY',
    options: ['Kamen Rider Zero-One', 'Kamen Rider Saber', 'Kamen Rider Revice', 'Kamen Rider Zeztz'],
    correctIndex: 3,
  },
  {
    id: 29,
    songTitle: 'EX-AID BGM & Level Up',
    series: 'Kamen Rider Ex-Aid',
    artist: 'Katsuyuki Harada',
    albumTitle: 'Ex-Aid OST',
    era: 'Heisei',
    themeColor: '#fa0079',
    audioUrl: '/songs/ex-aid-theme.mp3',
    youtubeId: 'fRSaJp362bM',
    options: ['Kamen Rider Ex-Aid', 'Kamen Rider Ghost', 'Kamen Rider Build', 'Kamen Rider Drive'],
    correctIndex: 0,
  },
  {
    id: 30,
    songTitle: 'My-Th Special Theme',
    series: 'Kamen Rider My-Th',
    artist: 'Kamen Rider Special',
    albumTitle: 'Special Opening',
    era: 'Reiwa',
    themeColor: '#10b981',
    audioUrl: '/songs/myth.mp3',
    youtubeId: 'kJOSoal4cTc',
    options: ['Kamen Rider Gavv', 'Kamen Rider My-Th', 'Kamen Rider Gotchard', 'Kamen Rider Geats'],
    correctIndex: 1,
  },
];

/**
 * Shuffle an array using Fisher-Yates algorithm
 */
export function shuffleArray<T>(array: T[]): T[] {
  const shuffled = [...array];
  for (let i = shuffled.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [shuffled[i], shuffled[j]] = [shuffled[j], shuffled[i]];
  }
  return shuffled;
}

/**
 * Get a randomized set of questions for a game
 */
export function getGameQuestions(count: number = 10): Question[] {
  const shuffled = shuffleArray(QUESTIONS);
  return shuffled.slice(0, Math.min(count, QUESTIONS.length));
}

/**
 * Calculate score based on time taken
 * Max: 1000 points (instant answer)
 * Min: 0 points (after 15 seconds)
 */
export function calculateScore(timeTakenMs: number, isCorrect: boolean): number {
  if (!isCorrect) return 0;
  return Math.max(0, 1000 - Math.floor(timeTakenMs / 15));
}

/**
 * Round time limit in milliseconds
 */
export const ROUND_TIME_LIMIT_MS = 15000;

/**
 * Time to show results between rounds (ms)
 */
export const RESULTS_DISPLAY_TIME_MS = 8000;
